### ISSUE TITLE
Calling Differential peaks consistent between biological replicates

### ISSUE THREAD

**Issue by chiefcat** [shao-lab/MAnorm#3]
Dear MAnorm developer,

Hi, I'm struggling with the workflow when calling differential peaks using MAnorm.
The experimental setting is like this:

Samples I've got:
Sample 1 Control, rep1 (MACS2 called peaks, read files)
Sample 2 Control, rep2 (MACS2 called peaks, read files)
Sample 3 Treatment, rep1 (MACS2 called peaks, read files)
Sample 4 Treatment, rep2 (MACS2 called peaks, read files)

Goal: I would like to identify Control biased, Treatment biased, and Unbiased peaks happen in both rep1 and rep2.

I'm not sure in which step I should pull the rep1 and rep2 together.

I've thought of 3 approaches, which approach is correct, or do you have any other suggestions?
Approach 1:
Step 1a.: Identify Control rep1 & rep2 unbiased peaks by MAnorm (Output merge peaks between rep1 &2)
Step 1b.: Identify Treatment rep1 & rep2 common peaks by MAnorm (Output merge peaks between rep1 &2)
Step 2.: Differential peak calling between Control & Treatment using the unbiased peaks from Step1a & 1b.

Approach 2:
Step1.: Construct a consensus peak set, which contains all peak coordinates from the 4 samples (merge peaks coordinate whenever overlapped) by bedtools
Step2a. : Perform differential peak calling for rep1 (Control, rep1 vs Treatment, rep1)
Step2b. : Perform differential peak calling for rep2 (Control, rep2 vs Treatment, rep2)
Step3.: Find out the rep1 & rep2 consistent differential peaks by coordinate overlapping (peaks coordinate from rep1 & rep2 are identical)

Approach 3:
Step1a. : Perform differential peak calling for rep1 (Control, rep1 vs Treatment, rep1)
Step1b. : Perform differential peak calling for rep2 (Control, rep2 vs Treatment, rep2)
Step3.: Identify rep1 and rep2 consistent differential peaks by coordinate overlapping (peaks coordinate from rep1 & rep2 are different, output the merged or interest coordinates)

Thanks! Hoping very much for your reply.

Kylie

**Comment by hongduosun** [comment]
Answered by email.

**Comment by AlicePsyche** [comment]
Hi, 

Sorry for the interruption, I have the exact same question. Could you please share your answers here? I believe this would help many people who are not bioinformatics guru... 

Thanks for your help in advance!

**Comment by hongduosun** [comment]
@AlicePsyche Below are my answers:

MAnorm is originally designed for 2 samples comparison (1 treatment with 1 control), but the approaches you mentioned are possible to call differential peaks with biological replicates.

Approach 1 is more applicable if you want to identify a set of most "reliable" differential peaks between treatment and control (firstly identify a set of high-confidence unbiased peaks within the same condition and then compare them).

Approach 2 will give you more candidate differential peaks than approach 3 because the initial peaks only need to be called in one sample, whereas approach 3 is something like what we usually do for 2 samples comparison (compare treatment and control of each replicate individually and take the intersection).

You can test these approaches with related downstream analysis to see which one performs better. Sometimes it is much more complicated than simply pool the ChIP-seq samples together for comparison with multiple replicates especially when samples have high variation.
